### ISSUE TITLE
CrossStoreReview.Current.OpenStoreReviewPage and CrossStoreReview.Current.OpenStoreListing not working on IOS 18

### ISSUE THREAD

**Issue by geogian98** [jamesmontemagno/StoreReviewPlugin#55]
Hey James!

I m using Plugin.StoreReview with version 6.2.0.
I just found that CrossStoreReview.Current.OpenStoreReviewPage and CrossStoreReview.Current.OpenStoreListing are not working on IOS 18, more exactly nothing is happened when I call them and there is no exception thrown.

Am I doing something wrong or there is an issue with the plugin?

Thanks a lot! I really appreciate you work!!

**Comment by mikebaumannch** [comment]
The `UIApplication.SharedApplilcation.OpenUrl(url)` is [deprecated](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl) since iOS 10. Looks like apple removed the support by introducing iOS 18.

Because this plugin is using the deprecated overload of the OpenUrl method, iOS won't be able to open the store by url:
https://github.com/jamesmontemagno/StoreReviewPlugin/blob/master/src/StoreReview.Plugin/StoreReviewImplementation.apple.cs#L39
& 
https://github.com/jamesmontemagno/StoreReviewPlugin/blob/master/src/StoreReview.Plugin/StoreReviewImplementation.apple.cs#L66

There is a new [overload](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open) available for this api:
`UIApplication.SharedApplication.OpenUrl(new NSUrl(url), newUIApplicationOpenUrlOptions(), null);
`
The new overload will work :-) Unfortunately, I am not able to create a PR for this...

**Comment by thomasgalliker** [comment]
It looks like this plugin is no longer maintained... do you guys use another plugin or is this code integrated in .NET MAUI meanwhile?

**Comment by geogian98** [comment]
@thomasgalliker I had the issue only on IOS so to make it work I did: public async Task OpenStorePage(string appId)
        {
            if (DeviceInfo.Platform == DevicePlatform.iOS)
            {
                var result = await TryOpenUriAsync($"itms-apps://itunes.apple.com/app/id{appId}");
                if (result)
                    return;

                await Launcher.TryOpenAsync($"https://apps.apple.com/app/id{appId}");
            }
            else if (DeviceInfo.Platform == DevicePlatform.Android)
            {
                CrossStoreReview.Current.OpenStoreListing(appId);
            }
        }

        public async Task OpenStoreReviewPage(string appId)
        {
            if (DeviceInfo.Platform == DevicePlatform.iOS)
            {
                var result = await TryOpenUriAsync($"itms-apps://itunes.apple.com/app/id{appId}?action=write-review");
                if (result)
                    return;

                await Launcher.TryOpenAsync($"https://apps.apple.com/app/id{appId}?action=write-review");
            }
            else if (DeviceInfo.Platform == DevicePlatform.Android)
            {
                CrossStoreReview.Current.OpenStoreReviewPage(appId);
            }
        }

I use it on a native Xamarin project .net8. I expect to work also on MAUI

**Comment by thomasgalliker** [comment]
Yeah it works on MAUI, thanks for the hint. I‘m just curious if there is a better store handling plugin for MAUI? Im not a big fan of having patches everywhere in my code. It looks like this plugin is no longer maintained. Maybe I‘m wrong.
